---
baseurl: /
locale: en-us
title: Webhippie United

disableKinds:
  - rss

params:
  Description: Software- und Web-Entwicklung
  Author: Webhippie United
  Website: https://webhippie.de
  Github: webhippie

module:
  mounts:
    - source: content
      target: content
    - source: static
      target: static
    - source: layouts
      target: layouts
    - source: data
      target: data
    - source: assets
      target: assets
    - source: i18n
      target: i18n
    - source: archetypes
      target: archetypes

    - source: node_modules/@fontsource/alegreya-sans-sc/files/alegreya-sans-sc-latin-400-normal.woff
      target: static/fonts/alegreya-sans-sc-latin-400-normal.woff

    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: assets/vendor/bootstrap.js

    - source: node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts

security:
  allowContent:
    - text/html

...
